
-- Creating processed streaming tables
-- BTC
CREATE OR REPLACE TABLE MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.BTC_PRICE (
    TRADE_TIME TIMESTAMP,
    CREATEDTIME TIMESTAMP,
    SYMBOL VARCHAR,
    AVG_PRICE NUMBER(38, 2),
    VOLUME NUMBER(38, 8)
);

-- ETH
CREATE OR REPLACE TABLE MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.ETH_PRICE (
    TRADE_TIME TIMESTAMP,
    CREATEDTIME TIMESTAMP,
    SYMBOL VARCHAR,
    AVG_PRICE NUMBER(38, 2),
    VOLUME NUMBER(38, 8)
);


-- transforming raw data
-- ingest to BTC table
INSERT INTO MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.BTC_PRICE
SELECT 
    DATE_TRUNC('second', TO_TIMESTAMP_NTZ(rc.value:t::NUMBER / 1000)) AS TRADE_TIME, 
    MIN(TO_TIMESTAMP_NTZ(rm:"CreateTime"::NUMBER / 1000)) AS CREATEDTIME, 
    rc.value:s::VARCHAR AS SYMBOL,
    AVG(rc.value:p::NUMBER(38, 2)) AS AVG_PRICE, 
    SUM(rc.value:v::NUMBER(38, 8)) AS VOLUME 
FROM MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.MSK_STREAMING_TBL,
     LATERAL FLATTEN(input => RECORD_CONTENT:data) rc, 
     LATERAL (SELECT PARSE_JSON(RECORD_METADATA) AS rm) 
WHERE rc.value:s = 'BINANCE:BTCUSDT'
GROUP BY 
    DATE_TRUNC('second', TO_TIMESTAMP_NTZ(rc.value:t::NUMBER / 1000)), 
    rc.value:s 
ORDER BY 
    TRADE_TIME;

-- ingest into ETH table
INSERT INTO MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.ETH_PRICE
SELECT 
    DATE_TRUNC('second', TO_TIMESTAMP_NTZ(rc.value:t::NUMBER / 1000)) AS TRADE_TIME, 
    MIN(TO_TIMESTAMP_NTZ(rm:"CreateTime"::NUMBER / 1000)) AS CREATEDTIME, 
    rc.value:s::VARCHAR AS SYMBOL,
    AVG(rc.value:p::NUMBER(38, 2)) AS AVG_PRICE, 
    SUM(rc.value:v::NUMBER(38, 8)) AS VOLUME 
FROM MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.MSK_STREAMING_TBL,
     LATERAL FLATTEN(input => RECORD_CONTENT:data) rc, 
     LATERAL (SELECT PARSE_JSON(RECORD_METADATA) AS rm) 
WHERE rc.value:s = 'BINANCE:ETHUSDT'
GROUP BY 
    DATE_TRUNC('second', TO_TIMESTAMP_NTZ(rc.value:t::NUMBER / 1000)), 
    rc.value:s 
ORDER BY 
    TRADE_TIME;

-- check
SELECT * FROM MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.BTC_PRICE;
SELECT * FROM MSK_STREAMING_DB.MSK_STREAMING_SCHEMA.ETH_PRICE;