CREATE OR REPLACE STORAGE INTEGRATION IMPORT_FINNHUB_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::169961544497:role/SnowflakeRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://import-finnhub/');


DESC INTEGRATION IMPORT_FINNHUB_INT;
  -- STORAGE_AWS_IAM_USER_ARN: arn:aws:iam::905418160770:user/9wxn0000-s
  -- STORAGE_AWS_EXTERNAL_ID: MI76435_SFCRole=2_uI4Nui3RseO2btBxeQyw9zTS76A=


CREATE OR REPLACE DATABASE BATCH_DB;
CREATE SCHEMA IF NOT EXISTS LANDING_FINNHUB;
CREATE SCHEMA IF NOT EXISTS HISTORY_FINNHUB;
CREATE SCHEMA IF NOT EXISTS REPLICA_FINNHUB;


CREATE OR REPLACE STAGE BATCH_DB.LANDING_FINNHUB.NEWS
    URL = 's3://import-finnhub/'
    STORAGE_INTEGRATION = IMPORT_FINNHUB_INT
    DIRECTORY = (ENABLE = TRUE AUTO_REFRESH = TRUE);


CREATE OR REPLACE TABLE BATCH_DB.LANDING_FINNHUB.FINNHUB_NEWS (
	CATEGORY VARCHAR,
	DATETIME NUMBER,
	HEADLINE VARCHAR,
	ID NUMBER,
	IMAGE VARCHAR,
	RELATED VARCHAR,
	SOURCE VARCHAR,
	SUMMARY VARCHAR,
	URL VARCHAR
);


CREATE OR REPLACE FILE FORMAT BATCH_DB.LANDING_FINNHUB.NEWS
TYPE = JSON
STRIP_OUTER_ARRAY = TRUE;


CREATE OR REPLACE PIPE BATCH_DB.LANDING_FINNHUB.NEWS
AUTO_INGEST = TRUE
AS
COPY INTO BATCH_DB.LANDING_FINNHUB.FINNHUB_NEWS
FROM (
  SELECT 
    $1:category::VARCHAR AS CATEGORY,
    $1:datetime::NUMBER AS DATETIME,
    $1:headline::VARCHAR AS HEADLINE,
    $1:id::NUMBER AS ID,
    $1:image::VARCHAR AS IMAGE,
    $1:related::VARCHAR AS RELATED,
    $1:source::VARCHAR AS SOURCE,
    $1:summary::VARCHAR AS SUMMARY,
    $1:url::VARCHAR AS URL
  FROM @BATCH_DB.LANDING_FINNHUB.NEWS
)
FILE_FORMAT = (FORMAT_NAME = 'BATCH_DB.LANDING_FINNHUB.NEWS');


SHOW PIPES;
-- arn:aws:sqs:eu-north-1:905418160770:sf-snowpipe-AIDA5FTZAXKBIQ6O6JCSA-yyf1-5IAzBuRY8wfBh8Rgg


select SYSTEM$PIPE_STATUS( 'NEWS' );


SELECT * FROM LANDING_FINNHUB.FINNHUB_NEWS;



CALL BATCH_DB.LANDING_FINNHUB.PROCESS_FINNHUB_NEWS();


SELECT * FROM BATCH_DB.REPLICA_FINNHUB.FINNHUB_NEWS;
SELECT * FROM BATCH_DB.HISTORY_FINNHUB.FINNHUB_NEWS;
SELECT * FROM BATCH_DB.LANDING_FINNHUB.FINNHUB_NEWS;


CREATE OR REPLACE TASK BATCH_DB.LANDING_FINNHUB.PROCESS_FINNHUB_NEWS_DAILY
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 6 * * * Europe/Helsinki'
AS
CALL BATCH_DB.PROCEDURES.PROCESS_FINNHUB_NEWS();


ALTER TASK BATCH_DB.LANDING_FINNHUB.PROCESS_FINNHUB_NEWS_DAILY RESUME;
